version: '3'
services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        restart: always
        ports:
            - '8000:8000'
        depends_on:
            - rabbitMQ
    celery:
        container_name: celery-worker
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        restart: always
        links:
            - rabbitMQ
            - mongo
        depends_on:
            - rabbitMQ
            - mongo
    rabbitMQ:
        container_name: rabbitMQ
        image: 'rabbitmq:3.7-management'
        restart: always
        env_file:
            - "./docker/rabbitmq/rabbitmq.env"
        ports:
            - '5672:5672'
            - '15672:15672'
    mongo:
        container_name: mongo-rabbit
        build:
            context: .
            dockerfile: ./docker/mongo/Dockerfile
        # hostname: mongo
        ports:
            - "27017:27017"
